version: 0.1
env:
  parameter-store:
    S3_BUCKET: "my_s3_bucket"
    
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket $S3_BUCKET  --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml